# Generated by Django 5.1.7 on 2025-09-22 14:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_organica', models.CharField(max_length=255, verbose_name='Unidad orgánica')),
                ('siglas', models.CharField(max_length=50, verbose_name='Siglas')),
                ('padre', models.CharField(blank=True, help_text='Siglas del área padre. Dejar en blanco si es un área principal.', max_length=50, null=True, verbose_name='Padre (siglas)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre_anterior', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre anterior')),
            ],
            options={
                'verbose_name': 'Estructura organizativa',
                'verbose_name_plural': 'Estructuras organizativas',
                'db_table': 'CONTROL_ACCESO_ESTRUCTURA',
                'ordering': ['siglas'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('tarjetavisita', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tarjeta de visita')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.BinaryField(blank=True, editable=True, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, help_text='Los administradores pueden ver todas las sedes', verbose_name='Es administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_acceso.sede', verbose_name='Sede asignada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('hora_entrada', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de entrada')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('receptor_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del receptor')),
                ('receptor_apellido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido del receptor')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_acceso.estructura', verbose_name='Área')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_acceso.person', verbose_name='Persona')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_acceso.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-fecha', '-hora_entrada'],
            },
        ),
    ]
